/* Copyright (C) LavaLite Contributors
 * GPL v2
 */
#pragma once

#include "ll.protocol.h"

/*
 * auth - HMAC-SHA256 authentication for the batch protocol.
 *
 * Client signs the outgoing protocol_header before sending.
 * mbd verifies the header before dispatching to any handler.
 * Responses from mbd to client are not signed.
 *
 * Key file: $LL_CONF_DIR/auth.key
 *   32 raw random bytes, mode 0640, group lavalite.
 *   Generated by mbd at startup if missing.
 *
 * Replay protection: mbd rejects headers older than AUTH_MAX_AGE seconds.
 */

#define AUTH_KEY_SIZE  32
#define AUTH_MAX_AGE   60

int auth_load_key(void);
int auth_generate_key(void);
int auth_sign_header(struct protocol_header *);
int auth_verify_header(const struct protocol_header *);
