#
# This file is a standard Bourne shell–style script.
# It is sourced by all LavaLite daemons and commands at startup
# to set up the cluster environment and runtime parameters.
#
# This my cluster name
LL_CLUSTER_NAME=lavalite

# Deamons state directories
LL_STATE_DIR=/opt/lavalite-1.0.0/var/state

# Daemon log messages
LL_LOG_DIR=/opt/lavalite-1.0.0/var/log
LL_LOG_MASK=LOG_DEBUG
#LL_LOG_MASK=LOG_WARNING

# Daemons listening ports must not
# be in use by other programs.
LL_MBD_PORT=33124
LL_MBD_HOST=mymbd
LL_MBD_USER=lavalite
LL_SBD_PORT=33125
LL_DEFAULT_QUEUE = myqueue

# Debug parameters used by development
# LL_API_CONNTIMEOUT=86400
# LL_API_RECVTIMEOUT=86400
# LL_SBD_CONNTIMEOUT=86400
# LL_SBD_READTIMEOUT=86400
# LL_ASSERT_COUNTERS=1
# LL_MBD_JOB_FINISH_THRESHOLD=1000
# LL_SBD_JOB_FINISH_RETAIN=100
