#
# This file is a standard Bourne shell–style script.
# It is sourced by all LavaLite daemons and commands at startup
# to set up the cluster environment and runtime parameters.
#
# This my cluster name
LL_CLUSTER_NAME=lavalite

LL_SERVERDIR=/opt/lavalite-1.0/sbin
LL_BINDIR=/opt/lavalite-1.0/bin
LL_SHAREDIR=/opt/lavalite-1.0/var/work
LL_ENVDIR=/opt/lavalite-1.0/etc

# Configuration directories
LL_CONFDIR=/opt/lavalite-1.0/etc

# Daemon log messages
LL_LOGDIR=/opt/lavalite-1.0/var/log
LL_LOG_MASK=LOG_DEBUG
#LL_LOG_MASK=LOG_WARNING

# Daemons listening ports must not
# be in use by other programs.
LL_LIM_PORT=33123
LL_MBD_PORT=33124
LL_SBD_PORT=33125
LL_EVENTS_MAX_SIZE=100M      # trigger compaction when file hits this
LL_EVENTS_RETAIN=24h         # keep finished jobs for this long

# Debug parameters used by development
# LL_API_CONNTIMEOUT=86400
# LL_API_RECVTIMEOUT=86400
# LL_SBD_CONNTIMEOUT=86400
# LL_SBD_READTIMEOUT=86400
# LL_API_CONNTIMEOUT=86400
# LL_API_RECVTIMEOUT=86400
# LL_MAX_SCHED_STAY=86400
