#
# This file is a standard Bourne shell–style script.
# It is sourced by all LavaLite daemons and commands at startup
# to set up the cluster environment and runtime parameters.
#
LL_SERVERDIR=/opt/lavalite/sbin
LL_BINDIR=/opt/lavalite/bin
LL_SHAREDIR=/opt/lavalite/var/work
LL_ENVDIR=/opt/lavalite/etc

# Configuration directories
LL_CONFDIR=/opt/lavalite/etc

# Daemon log messages
LL_LOGDIR=/opt/lavalite/var/log
LL_LOG_MASK=LOG_DEBUG
#LL_LOG_MASK=LOG_WARNING

# Daemons listening ports must not
# be in use by other programs.
LL_LIM_PORT=55535
LL_MBD_PORT=55536
LL_SBD_PORT=55537
#
# Use eauth authentication.
LL_AUTH=eauth

# Debug parameters used by development
# LL_NO_FORK=y
# LL_API_CONNTIMEOUT=86400
# LL_API_RECVTIMEOUT=86400
# LL_SBD_CONNTIMEOUT=86400
# LL_SBD_READTIMEOUT=86400
# LL_API_CONNTIMEOUT=86400
# LL_API_RECVTIMEOUT=86400
LL_EVENTS_MAX_SIZE=100M      # trigger compaction when file hits this
LL_EVENTS_RETAIN=24h         # keep finished jobs for this long
LL_CLUSTER_NAME=lavalite
